// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JicoIyBZ2pZvLpER6p_FUdCfMYua2Kk',
    appId: '1:1076867009851:android:6b243efb9f478f3269bb1e',
    messagingSenderId: '1076867009851',
    projectId: 'bookmarket-999999',
    storageBucket: 'bookmarket-999999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwxPdP0gad4lEKevcKaXMrav8txFz20o',
    appId: '1:1076867009851:ios:06483ccd810226a969bb1e',
    messagingSenderId: '1076867009851',
    projectId: 'bookmarket-999999',
    storageBucket: 'bookmarket-999999.appspot.com',
    iosClientId: '1076867009851-sa4o65l6c0mth3la9r3jvbfcn6kggm23.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmarket',
  );
}
